/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ServiceType = IDL.Variant({
  'commercialCleaning' : IDL.Null,
  'residentialCleaning' : IDL.Null,
  'carDetailing' : IDL.Null,
  'carpetCleaning' : IDL.Null,
});
export const Time = IDL.Int;
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'serviceType' : ServiceType,
  'serviceAddress' : IDL.Text,
  'contactInfo' : IDL.Text,
  'preferredDate' : Time,
});

export const idlService = IDL.Service({
  'createBooking' : IDL.Func(
      [IDL.Text, IDL.Text, ServiceType, Time, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
  'getBookingsByCustomer' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ServiceType = IDL.Variant({
    'commercialCleaning' : IDL.Null,
    'residentialCleaning' : IDL.Null,
    'carDetailing' : IDL.Null,
    'carpetCleaning' : IDL.Null,
  });
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'serviceType' : ServiceType,
    'serviceAddress' : IDL.Text,
    'contactInfo' : IDL.Text,
    'preferredDate' : Time,
  });
  
  return IDL.Service({
    'createBooking' : IDL.Func(
        [IDL.Text, IDL.Text, ServiceType, Time, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
    'getBookingsByCustomer' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Booking)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };